config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "users/show"
  get "user/show"
  root "todos#index"
  get "/refresh", to: "todos#refresh", as: :refresh_todos
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/faraday_logging.rb
# frozen_string_literal: true

# Path: app/models/faraday_logging.rb
class FaradayLogging < ::Faraday::Middleware
  def on_complete(env)
    Rails.logger.info(
      message: "#{env.method.to_s.upcase} #{env.url}",
      event: {
        name: "http.request.made"
      },
      http: {
        request: {
          method: env.method.to_s.upcase,
          headers: env.request_headers,
          body: env.request_body,
          url: env.url
        },
        response: {
          status_code: env.response.status,
          headers: env.response_headers,
          body: env.response_body
        }
      }
    )
  end

  def filter
    @filter ||= ActiveSupport::ParameterFilter.new(Rails.configuration.filter_parameters)
  end
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/models/typicode/todo.rb
# frozen_string_literal: true

module Typicode
  # Path: app/models/typicode/todo.rb
  class Todo < Dry::Struct
    attribute :id, Dry.Types::Integer
    attribute :title, Dry.Types::String
    attribute :completed, Dry.Types::Bool

    def self.all
      api.get("/todos").body.map { |todo| new(todo) }
    end

    def self.api
      Faraday.new(url: "https://jsonplaceholder.typicode.com/todos") do |conn|
        conn.use FaradayLogging
        conn.request :json
        conn.response :json, parser_options: {symbolize_names: true}
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable, :confirmable

  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
# frozen_string_literal: true

# Path: app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :authenticate_user!

  def index
    @todos = Todo.all
  end

  def refresh
    Todos::Refresh.new.call_async
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    UpdateUserAnalyticsJob.perform_later(@user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsObservabilityPlaybook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if current_user %>
      <p>Signed In as <%= current_user.email %></p>
      <p><%= link_to "Sign Out", destroy_user_session_path, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/todos/index.erb
<h1>Here are your todos</h1>

<%= link_to 'Refresh', refresh_todos_path %>

<% if @todos.empty? %>
  <p>You have no todos</p>
<% else %>
  <ul>
    <% @todos.each do |todo| %>
      <li><%= todo.title %></li>
    <% end %>
  </ul>
<% end %>

app/views/users/show.html.erb
<h1>Profile for user <%= @user.id %></h1>